name: Feedback
description: For giving thanks, general discussion etc.
title: '[FEEDBACK] '
labels:
  - 'type: Feedback'
assignees: []
body:

- type: markdown
  id: notice
  attributes:
    value: |
      :warning: This form is for feedback specifically about the BibleTime software itself. If your feedback relates to specific content such as Bibles, commentaries, books, lexicons, or their metadata or availability, please direct that to the appropriate content providers rather than this issue tracker.

- type: checkboxes
  id: i_have_read_and_i_agree
  attributes:
    label: Acknowledgment
    options:
      - label: I have read and respect the notice that was displayed when I submitted this form.
        required: true
  validations:
    required: true

- type: textarea
  id: feedback
  attributes:
    label: Feedback
  validations:
    required: true
