name: Windows CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  Windows:
    name: build-windows
    runs-on: [windows-2022]

    steps:
    - name: Checkout qtdeclarative
      uses: actions/checkout@v5
      with:
        repository: qt/qtbase
        ref: v6.9.2
        path: qtbase

    - name: Install qtbase
      run: |
        New-Item -ItemType Directory -Path qtbase_build
        Set-Location qtbase_build
        ../qtbase/configure -icu
        cmake --build . --parallel
        cmake --install .
        Set-Location ..
        Remove-Item -Path qtbase_build
        Remove-Item -Path qtbase

    steps:
    - name: Checkout qtdeclarative
      uses: actions/checkout@v5
      with:
        repository: qt/qtdeclarative
        ref: v6.9.2
        path: qtdeclarative

    - name: Install qtdeclarative
      run: |
        New-Item -ItemType Directory -Path qtdeclarative_build
        Set-Location qtdeclarative_build
        ../qtdeclarative/configure
        cmake --build . --parallel
        cmake --install .
        Set-Location ..
        Remove-Item -Path qtdeclarative_build
        Remove-Item -Path qtdeclarative

    steps:
    - name: Checkout qtsvg
      uses: actions/checkout@v5
      with:
        repository: qt/qtsvg
        ref: v6.9.2
        path: qtsvg

    - name: Install qtsvg
      run: |
        New-Item -ItemType Directory -Path qtsvg_build
        Set-Location qtsvg_build
        ../qtsvg/configure -icu
        cmake --build . --parallel
        cmake --install .
        Set-Location ..
        Remove-Item -Path qtsvg_build
        Remove-Item -Path qtsvg
