name: Windows CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  Windows:
    name: build-windows
    runs-on: [windows-2022]
    env:
      ICU_ROOT: ${{ github.workspace }}/icu
    steps:
    - uses: actions/checkout@v5
    - name: Install dependencies
      run: vcpkg install
