name: Windows CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  Windows:
    name: build-windows
    runs-on: [windows-2022]
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-rel
      VCPKG_DISABLE_METRICS: 1
      ICU_ROOT: ${{ github.workspace }}/icu
    steps:

    - uses: actions/checkout@v5

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 120deac3062162151622ca4860575a33844ba10b # 2025.08.27

    - name: Install NSIS
      run: choco install nsis

    - name: Build
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'msbuild-vcpkg'
        buildPreset: 'msbuild-vcpkg'
        buildPresetAdditionalArgs: "['--config Release']"

    - name: Save BibleTime Installer
      uses: actions/upload-artifact@v4
      with:
        name: bibletime-x64-installer
        path: build\bibletime-prefix\src\bibletime-build\BibleTime-${{env.BT_VERSION}}-win64.exe
        retention-days: 5
