name: Windows CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  Windows:
    name: build-windows
    runs-on: [windows-2019]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download Qt
      run: |
        Invoke-WebRequest -Uri https://download.qt.io/official_releases/qt/6.9/6.9.2/single/qt-everywhere-src-6.9.2.zip -OutFile qt-everywhere-src-6.9.2.zip
        Expand-Archive -Path qt-everywhere-src-6.9.2.zip
        mkdir qtbuild
        cd qtbuild
        ../qt-everywhere-src-6.9.2/configure -icu
