name: Windows CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  Windows:
    name: build-windows
    runs-on: [windows-2022]
    env:
      ICU_ROOT: ${{ github.workspace }}/icu
    steps:

    - uses: actions/checkout@v5

    - name: Install dependencies from vcpkg
      run: vcpkg install

    - name: Install NSIS
      run: choco install nsis

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: Save BibleTime Installer
      uses: actions/upload-artifact@v4
      with:
        name: bibletime-x64-installer
        path: build\bibletime-prefix\src\bibletime-build\BibleTime-${{env.BT_VERSION}}-win64.exe
        retention-days: 5
