name: Windows CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  Windows:
    name: build-windows
    runs-on: [windows-2022]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download qtbase
      run: |
        Invoke-WebRequest -Uri https://github.com/qt/qtbase/archive/refs/tags/v6.9.2.zip -OutFile qtsrc.zip
        Expand-Archive -Path qtsrc.zip
        mkdir qtbuild
        cd qtbuild
        ../qtsrc/configure -icu
